- hosts: network
  become: yes
  tasks: 
    - name: Install web components
      package: name={{item}} state=latest
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv
